const paragraphs = [
    "BICTE (Bachelor of Education in Information Communication Technology) is a four-year undergraduate program offered by Tribhuvan University in Nepal. It is designed to integrate modern education systems with computer science, focusing on subjects like Information Technology, Programming (C/C++ and Java), Database Management, Data Communication, and Artificial Intelligence.",
    "Information and Communication Technology (ICT) refers to the integration of telecommunications, computing devices, software applications, and networks that facilitate the storage, transmission, and processing of information. It encompasses a wide range of technologies, including the internet, mobile communication, cloud computing, artificial intelligence, and digital media, all of which play a crucial role in modern society.",
    "Technology and Innovation Technology has revolutionized the way humans live, work, and interact. From smartphones to artificial intelligence, advancements have made life more efficient and connected. The rapid growth of innovation continues to shape industries, with automation and digital transformation streamlining processes. As technology evolves, ethical considerations and cybersecurity become critical areas of focus. The future holds endless possibilities, ensuring that progress never stops.",
    "The Importance of Education Education is the key to individual growth and societal development. It provides knowledge, skills, and perspectives that empower people to make informed decisions. Learning is a lifelong process that extends beyond classrooms, encouraging curiosity and critical thinking. With the rise of online education, access to learning has become more inclusive and flexible. A well-educated society fosters innovation, equality, and economic advancement.",
    "The Beauty of Nature Nature offers breathtaking landscapes and peaceful moments that refresh the mind and soul. From towering mountains to vast oceans, the planet is filled with wonders that inspire awe. Forests provide oxygen, wildlife thrives in harmony, and ecosystems maintain balance. Protecting nature is essential to preserving biodiversity and ensuring a sustainable future. A single sunset or blooming flower reminds us of the simplicity and beauty of life.",
    "The Power of Positivity A positive mindset can shape one's experiences and overall well-being. Optimism encourages resilience, helping people overcome challenges with confidence and hope. Surrounding oneself with supportive individuals fosters motivation and emotional strength. Simple actions, like gratitude and kindness, contribute to a happier, healthier life. By embracing positivity, people create a ripple effect, influencing others in meaningful ways.",
    "The Value of Hard Work Hard work is the foundation of success, fueling achievements in personal and professional life. Dedication and perseverance allow individuals to push past obstacles and accomplish their goals. Every effort contributes to growth, building discipline and character along the way. While setbacks may occur, consistency and determination lead to long-term rewards.",

];